import Vue from 'vue';

import RowWidget from './RowWidget';
import ColWidget from './ColWidget';
import CardWidget from './CardWidget';
import TemplateWidget from './TemplateWidget';
import DialogWidget from './DialogWidget';
import ButtonWidget from './ButtonWidget';
import InputWidget from './InputWidget';
import SwitchWidget from './SwitchWidget';
import SelectWidget from './SelectWidget';
import OptionWidget from './OptionWidget';
import RadioGroupWidget from './RadioGroupWidget';
import RadioWidget from './RadioWidget';
import CheckboxGroupWidget from './CheckboxGroupWidget';
import CheckboxWidget from './CheckboxWidget';
import DatePickerWidget from './DatePickerWidget';
import TimePickerWidget from './TimePickerWidget';
import TableWidget from './TableWidget';
import TableColumnWidget from './TableColumnWidget';
import FormWidget from './FormWidget';
import FormItemWidget from './FormItemWidget';

Vue.component('row-widget', RowWidget);
Vue.component('col-widget', ColWidget);
Vue.component('card-widget', CardWidget);
Vue.component('template-widget', TemplateWidget);
Vue.component('dialog-widget', DialogWidget);
Vue.component('button-widget', ButtonWidget);
Vue.component('input-widget', InputWidget);
Vue.component('switch-widget', SwitchWidget);
Vue.component('select-widget', SelectWidget);
Vue.component('option-widget', OptionWidget);
Vue.component('radio-group-widget', RadioGroupWidget);
Vue.component('radio-widget', RadioWidget);
Vue.component('checkbox-group-widget', CheckboxGroupWidget);
Vue.component('checkbox-widget', CheckboxWidget);
Vue.component('date-picker-widget', DatePickerWidget);
Vue.component('time-picker-widget', TimePickerWidget);
Vue.component('table-widget', TableWidget);
Vue.component('table-column-widget', TableColumnWidget);
Vue.component('form-widget', FormWidget);
Vue.component('form-item-widget', FormItemWidget);
